---
- name: Copy custom heat templates files if provided
  template:
    src: "{{ item.value.src }}"
    dest: "{{ upgrade_working_dir }}/{{ item.value.name }}"
  with_dict: "{{ upgrade_templates }}"

- name: Copy ignore warnings template file for ceph upgrade
  template:
    src: "ceph-upgrade.yaml.J2"
    dest: "{{ upgrade_working_dir }}/ceph-upgrade.yaml"
  when: enable_ceph|bool

- name: Make sure no Tht repo is present
  when: not mixed_upgrade|bool
  file: path={{ upgrade_working_dir }}/{{ tht_dir }} state=absent

- name: Copy new Tht directory to the upgrade working dir
  when: not mixed_upgrade|bool
  shell: >
      cp -R /usr/share/openstack-tripleo-heat-templates \
      {{ upgrade_working_dir }}/{{ tht_dir }};

- name: Add the no ssh finger print checking into upgrade-non-controller.sh
  when: step_upgrade_undercloud
  sudo: yes
  shell: >
      sed -i 's/ssh/ssh -o StrictHostKeyChecking=no/' \
      {{ upgrade_non_controller_script }}

- name: allow traffic for the controller
  sudo: yes
  shell: >
        sudo iptables -A BOOTSTACK_MASQ -s {{ network_isolation_ipv4_cidr }} ! \
        -d {{ network_isolation_ipv4_cidr }} -j MASQUERADE -t nat;
        sudo iptables-save > /etc/sysconfig/iptables;
  when: network_isolation|bool and deployment_type == "virtual"

- name: Create major overcloud upgrade script
  when: major_upgrade
  template:
    src: "{{ major_upgrade_script }}"
    dest: "{{ upgrade_working_dir }}/overcloud-upgrade.sh"
    mode: 0755

- name: Create minor overcloud upgrade script
  when: not major_upgrade|bool
  template:
    src: "{{ minor_upgrade_script }}"
    dest: "{{ upgrade_working_dir }}/overcloud-upgrade.sh"
    mode: 0755
