---
- name: Execute yum update on the undercloud
  sudo: yes
  yum: name=* state=latest

- name: Upgrade the undercloud
  shell: openstack undercloud upgrade &> upgrade_undercloud.log
  when: step_upgrade_undercloud
  notify:
    - restart openstack services

- name: create vlan if doesn't exist
  ignore_errors: yes
  sudo: yes
  shell: >
    ifconfig {{ network_isolation_vlan }};
    if [[ $? != 0 ]]; then \
    ovs-vsctl add-port br-ctlplane {{ network_isolation_vlan }} tag={{ network_isolation_vlan_tag }} \
    -- set interface {{ network_isolation_vlan }} type=internal;
    fi
  when: network_isolation

- name: set vlan up
  ignore_errors: yes
  sudo: yes
  shell: >
    ip l set dev {{ network_isolation_vlan }} up;
  when: network_isolation